apiVersion: v1
kind: Service
metadata:
  name: onlinebookstore
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 31020
  selector:
    app: onlinebookstore
